name: Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '35 19 10 * *'  # 10th of the month at 7:35pm UTC

  workflow_dispatch:

jobs:

  # This job is a workaround for global variables
  # See https://github.com/actions/runner/issues/480
  Params:
    uses: Elmeric/my-gha-workflows/.github/workflows/Parameters.yml@dev
    with:
      name: dfacto
      # Optional
      system_list: 'ubuntu windows macos'
      python_version: '3.11'
      python_version_list: '3.9 3.10 3.11'
      exclude_list: "windows:3.9 windows:3.10 macos:3.9 macos:3.10"

  CodeCheck:
    uses: Elmeric/my-gha-workflows/.github/workflows/CodeCheck.yml@dev
    needs:
      - Params
    with:
      poetry-version: "1.5.1"
      commands: inv checks.all
      # Optional
      python_version: "3.11"

# https://stackoverflow.com/questions/75549995/why-do-the-pyside6-qt-modules-cause-tox-to-fail-during-a-github-action:
#      - name: Install dependencies
#        run: |
#          sudo apt update && sudo apt install -y libegl1-mesa-dev
  UnitTesting:
    uses: Elmeric/my-gha-workflows/.github/workflows/UnitTesting.yml@dev
    needs:
      - Params
      - CodeCheck
    with:
      jobs: ${{ needs.Params.outputs.python_jobs }}
      poetry-version: "1.5.1"
      commands: inv test -c dfacto --lcov

  Coverage:
    uses: Elmeric/my-gha-workflows/.github/workflows/CoverageCollection.yml@dev
    needs:
      - Params
      - UnitTesting
